### ISSUE TITLE
trouble while 'synchronizing with network'

### ISSUE THREAD

**Issue by Toporin** [ScripterRon/BitcoinWallet#1] opened 2015-02-06 11:12 UTC
I tried to run the Bitcoin wallet (on windows 8, java 8) but it seems the client get stuck during synchronization with network: the block number as displayed by the wallet remains at 0 (see screenshot below).

When I receive a new transaction, this is detected immediatly by the client and shown in the list of transactions in the main window, but the status of the transaction is stuck to 'pending'. Since the transaction is never confirmed, it cannot be spent.

I tried to run/reinstall the client several times and only once (by chance) the block number started to increase, but I don't know why. 

Can this problem be related with network configuration (router with NAT)?

BTW, great application!

![image](https://cloud.githubusercontent.com/assets/10826856/6078354/fed157ce-adf7-11e4-9613-c7a342366acf.png)

**Comment by ScripterRon** [comment] 2015-02-06 13:41
What is displayed in the console window?  Use java instead of javaw when starting BitcoinWallet to get a console window.

Another option is to log to a file instead of the console window.  This is a good idea anyways since debug logging can generate a lot of messages.

Attached is a sample logging.properties.  Put it in the application directory (%APPDATA%\BitcoinWallet) along with BitcoinWallet.conf.  The log file will be named BitcoinWallet.log and will be in your temporary directory (%LOCALAPPDATA%\temp).  Debug logging is enabled (FINE level).  After the problem is resolved, you can turn off debug logging by setting the log level to INFO for BitcoinWallet and BitcoinCore.

################################################
#  	BitcoinWallet Logging Configuration File                       #
#                                                                                             #
# Rename this file to logging.properties and place it in          #
# the BitcoinWallet application directory.  Change the log     #
# file name as desired (java.util.logging.FileHandler.pattern) #
#################################################

# Log to console and file
handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# Default logging level (FINE, INFO, WARNING, SEVERE)
.level = SEVERE

# BitcoinWallet logging level (FINE, INFO, WARNING, SEVERE)
org.ScripterRon.BitcoinWallet.level = FINE

# BitcoinCore logging level (FINE, INFO, WARNING, SEVERE)
org.ScripterRon.BitcoinCore.level = FINE

# Create log file in temporary directory, accept FINE or higher messages,
# maximum file size is 500KB with a single file
java.util.logging.FileHandler.pattern = %t/BitcoinWallet.log
java.util.logging.FileHandler.limit = 500000
java.util.logging.FileHandler.count = 1
java.util.logging.FileHandler.level = FINE

# Limit the message that are printed on the console to FINE and above
java.util.logging.ConsoleHandler.level = FINE

**Comment by ScripterRon** [comment] 2015-02-06 13:49
See my comment on GitHub.  Sorry for the multiple edits but it took me a
couple of tries to get GitHub to stop mangling the logging.properties
example.  I'll push a sample.logging.properties to GitHub as well

**Comment by ScripterRon** [comment] 2015-02-06 13:56
By the way, the block count staying at 0 is not necessarily a problem depending on how the blockchain is downloading.  BitcoinWallet builds from earliest to latest but it also builds from latest to earliest (since a block does not contain the block height within itself).  While working backwards, the displayed block number will stay at the last block which has a complete chain back to the genesis block.  The debug log will show what is happening.

**Comment by Toporin** [comment] 2015-02-07 16:50
Here is a pastebin of the log file including wallet start & stop (block counter remaining at 0):
http://pastebin.com/yS5q6PUV

This is an extract from a previous log in which the block counter was increasing in the wallet GUI:
http://pastebin.com/PvA3GqDS

**Comment by ScripterRon** [comment] 2015-02-07 17:20
The 'chain block not available' message occurs when working backwards from the last block in the chain.  It indicates that a block is missing in the chain back to the genesis block.  This is the scenario where the block number won't be increasing because a complete chain hasn't been established yet.  Each time a missing block is found, it is fetched from the peer.  You need to let it run until it fills in the missing blocks.  The last block listed in the log is at height 306771, so there is a long way to go yet.

Let it run for an hour and then check on its progress.  The initial synch takes a long time (there are over 340,000 blocks to process).  You can go to https://blockchain.info to check on the progress.  Just enter the latest block identifier from the log file into the search box.

**Comment by ScripterRon** [comment] 2015-02-07 17:43
Did you delete the database directory when you restarted?  The first log shows BitcoinWallet starting with a block height of 0.  The block height should have been the value it was at after the earlier run completed.

**Comment by ScripterRon** [comment] 2015-02-07 17:57
Hmm - I tried to create a new wallet from scratch and it failed with an exception.  I forgot to create the Database directory when I switched from LevelDB to H2.  This didn't cause me any problems in my testing because I was using an existing wallet.  I'll add code to create the directory and then try it again.

**Comment by ScripterRon** [comment] 2015-02-07 18:53
OK - there is something wrong here.  The blocks aren't being connected to the genesis block properly.  Don't do anything further until I have a chance to find out what is going wrong when creating a new database.

**Comment by ScripterRon** [comment] 2015-02-07 20:11
I found the problem (only happens with a new database).  Download Version 3.0.1 and extract the files (delete the existing files first so you don't get duplicates).  Delete the %APPDATA%\BitcoinWallet\Database directory so that the download will start from the beginning using headers-only (the slower merkle block download must be used with an existing database since BitcoinWallet needs to scan for matching transactions instead of just downloading the headers).  

Once the network synch has completed, you can create send/receive addresses as desired.  It is a good idea to export your private keys once you have created the receive addresses, since you will need to recreate the keys if your database is corrupted or deleted.  You should copy the export file to an offline media (thumb drive, CD-ROM, etc) and then delete the local copy so it can't be compromised.

You should also change the logging level from FINE to INFO to reduce the log file size.
<pre>
# BitcoinWallet logging level
org.ScripterRon.BitcoinWallet.level = INFO
org.ScripterRon.BitcoinCore.level = INFO
</pre>

I was able to create a new database without any problems, so you should be OK now.

**Comment by ScripterRon** [comment] 2015-02-07 20:22
Don't delete the database if you have already created receive addresses that contain bitcoins (the private keys will be lost if the database is deleted).  If you want to delete the database and start fresh, export the keys first.  Then delete the database and restart BitcoinWallet to build the new database.  Once the network synch is complete, import the keys into the new database and then rescan the block chain to pick up transactions using those keys.

Remember to export the keys whenever you add a new receive address.  BitcoinWallet does not automatically create keys other than the initial change address, so you don't need to worry about exporting keys at any other time.

**Comment by ScripterRon** [comment] 2015-02-07 20:53
One more thing: the Version 2 database is not compatible with Version 3.  If you are switching from Version 2, you need to export your private keys using BitcoinWallet Version 2.  You can then import the keys using BitcoinWallet Version 3.

**Comment by ScripterRon** [comment] 2015-02-08 21:44
Contact me at Ronald.Hoffman6@gmail.com if you are still experiencing problems

**Closed by ScripterRon** 2015-02-08 21:44 UTC
